site_name: Awesome Tools
site_url: https://qubitpi.github.io/awesome-tools
site_description: A curated list of awesome tools for dev, design, and life.
site_author: Jiaqi Liu
repo_name: QubitPi/awesome-tools
repo_url: https://github.com/QubitPi/awesome-tools
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
      link: https://github.com/QubitPi
extra_css:
    - css/extra.css
nav:
  - "If I can't fork it, I'll put it here": "index.md"
